export const people = [
	{
		id: 1,
		givenName: "Thomas",
		familyName: "Watson",
		dob: "1978-06-17",
		pob: "Los Angeles (United States)",
		profession: "Software Developer",
		email: "thomas.watson13@example.com",
	},
	{
		id: 2,
		givenName: "Jean",
		familyName: "Brooks",
		dob: "2000-07-10",
		pob: "Sydney (Australia)",
		profession: "Web Developer",
		email: "jean.brooks8@example.com",
	},
	{
		id: 3,
		givenName: "Lillian",
		familyName: "Taylor",
		dob: "1979-06-17",
		pob: "Auckland (New Zealand)",
		profession: "Carpenter",
		email: "lillian.taylor36@example.com",
	},
	{
		id: 4,
		givenName: "Philip",
		familyName: "Rogers",
		dob: "2001-12-05",
		pob: "Edinburgh (United Kingdom)",
		profession: "Software Developer",
		email: "philip.rogers63@example.com",
	},
	{
		id: 5,
		givenName: "Rachel",
		familyName: "Baker",
		dob: "1997-12-06",
		pob: "Sydney (Australia)",
		profession: "Civil Engineer",
		email: "rachel.baker59@example.com",
	},
];
